import './global.css';

export const metadata = {
  title: 'Welcome to lab-1-next-nav-time',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#191919] text-gray-200 min-h-screen">
        <div className="flex h-screen overflow-hidden">{children}</div>
      </body>
    </html>
  );
}
